# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and publish a new beta to TestFlight"
  lane :beta do
    project = "ScoreMatching.xcodeproj"
    version = get_version_number(xcodeproj: project, target: "What the score")
    local_build = get_build_number(xcodeproj: project).to_i
    testflight_build = latest_testflight_build_number(version: version, initial_build_number: 0)
    build_number = [local_build, testflight_build.to_i].max + 1

    increment_build_number(build_number: build_number.to_s, xcodeproj: project)

    ipa = build_app(
      project: project,
      scheme: "What the score",
      configuration: "Release",
      export_options: {
        method: "app-store-connect",
        signingStyle: "automatic",
        teamID: "382G4857JD",
        manageAppVersionAndBuildNumber: false
      },
      output_directory: "build/fastlane"
    )

    upload_to_testflight(
      ipa: ipa,
      skip_waiting_for_build_processing: false,
      distribute_external: false
    )
  end

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "ScoreMatching")
  end
end
